applications/empleados/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name ="empleado_app"

urlpatterns = [
    path('',
         views.StartView.as_view(),
         name='inicio'),

    path('listar-todos-empleados/',
         views.ListallEmpleados.as_view(),
         name='empleados-all'),

    path('listar-by-area/<nname>',
         views.ListbyArea.as_view(),
         name='empleados_area'),

    path('listar-empleados-admin',
         views.ListaEmpleadosAdmin.as_view(),
         name='empleados_admin'),

    path('buscar-empleado', views.ListbyKeyword.as_view()),

    path('lista-de-habilidades', views.ListHabEmp.as_view()),

    path('ver-empleado/<pk>/',
         views.EmpDetView.as_view(),
         name='empleado_detail'),

    path('add-empleado/',
         views.EmpCreateView.as_view(),
        name='empleado_add'),

    path('success/',
         views.SuccessView.as_view(),
         name='correcto'),

    path('update-empleado/<pk>/',
         views.EmpUpdView.as_view(),
         name='modificar_empleado'),

    path('deleted/',
         views.DeleteSuccessView.as_view(),
         name='deleted'),
    path('delete-empleado/<pk>',
         views.EmpDelView.as_view(),
         name='eliminar-empleado'),

     ]

urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('applications.home.urls')),
    path('',include('applications.departamento.urls')),
    path('',include('applications.empleados.urls')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/empleados/models.py
from django.db import models
from ..departamento.models import Departamento
from ckeditor.fields import RichTextField

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad',max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades Empleados'
        # ordering = ['-name']
        # unique_together = ('name','short_name')
    def __str__(self):
        return str(self.id) + '-'+self.habilidad



class Empleado(models.Model):
    JOB_CHOICES = (
        ('0','Contador'),
        ('1', 'Administrador'),
        ('2', 'Economista'),
        ('3', 'Otro'),
    )
    first_name = models.CharField('Nombres',max_length=60)
    last_name = models.CharField('Apellidos',max_length=120,blank=True)
    full_name = models.CharField('Nombres Completos',max_length=70)
    job = models.CharField('Trabajo', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleados', blank=True, null=True)
    #relacion de muchos a muchpos
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()

    def __str__(self):
        return str(self.id) + '-'+self.first_name + '-' + self.last_name

applications/empleados/forms.py
from django import forms
from .models import Empleado

class EmpleadoForm(forms.ModelForm):

    class Meta:
        model=Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets={
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/empleados/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView)

from .models import Empleado
from .forms import EmpleadoForm

class StartView(TemplateView):
    """view that loads start page"""
    template_name = 'inicio.html'


class ListallEmpleados(ListView):
    template_name = 'empleados/list_all.html'
    paginate_by = 3
    ordering = 'first_name'
    context_object_name = 'empleados'

    def get_queryset(self):

        palabra_clave = self.request.GET.get("kword",'')
        #jorge = j
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave
        )
        return lista
class ListaEmpleadosAdmin(ListView):
    template_name = 'empleados/list_empleados.html'
    paginate_by = 3
    ordering = 'first_name'
    context_object_name = 'empleados'
    model=Empleado


class ListbyArea(ListView):
    #lista empleados de un area
    template_name = 'empleados/list_by_area.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        #recoge lo que está mandando
        area = self.kwargs['nname']
        lista = Empleado.objects.filter(
        departamento__short_name__iexact=area

    )

        return lista

class ListbyKeyword(ListView):
    """Lista por palabras clave"""
    template_name = 'empleados/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        #print('wgfwefwef')
        #recebemos las solicitudes que envia el servidor mediante request
        palabra_clave = self.request.GET.get("kword",'')
        lista = Empleado.objects.filter(
            first_name__iexact=palabra_clave

        )
        return lista

class ListHabEmp(ListView):
    template_name = 'empleados/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=3)
        print(empleado.habilidades.all())
        return empleado.habilidades.all()

class EmpDetView(DetailView):
    model = Empleado
    template_name = "empleados/detail_empleado.html"

    def get_context_data(self, **kwargs):
        context = super(EmpDetView, self).get_context_data(**kwargs)
        print(context)
        context['titulo'] = 'Empleado del mes'
        return context

class EmpCreateView(CreateView):
    template_name = "empleados/add.html"
    model = Empleado
    form_class = EmpleadoForm
    success_url = reverse_lazy('empleado_app:empleados_admin')

    def form_valid(self,form):
        #logica del proceso
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name+' '+empleado.last_name
        empleado.save()
        print(empleado)
        return super(EmpCreateView,self).form_valid(form)


class SuccessView(TemplateView):
    template_name = "empleados/success.html"

class DeleteSuccessView(TemplateView):
    template_name = "empleados/deleted.html"

class EmpUpdView(UpdateView):
    model = Empleado
    template_name = "empleados/update.html"
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',

    ]

    success_url = reverse_lazy('empleado_app:empleados_admin')

    #guardar antes de ser validados por form_valid
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self,form):
        print('******Metodo form valid*****')
        return super(EmpUpdView,self).form_valid(form)

class EmpDelView(DeleteView):
    model = Empleado
    template_name = "empleados/deleteview.html"
    success_url = reverse_lazy('empleado_app:empleados_admin')

templates/empleados/add.html
{% extends 'base.html' %}

{% block title %}
    Registrar Empleado
{% endblock title %}

{% block content %}
{% include "includes/header.html" %}


<div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Registrar Empleado:</h1>
                <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}

                    <div class="cell large-6">
                            <label>Nombre:
                                {{form.first_name}}
                            </label>
                        </div>
                        <div class="cell large-6">
                            <label>Apellido:
                                {{form.last_name}}
                            </label>
                        </div>
                        <div class="cell large-6">
                            <label>Trabajo:
                                {{form.job}}
                            </label>
                        </div>
                        <div class="cell large-6">
                            <label>Area:
                                {{form.departamento}}
                            </label>
                        </div>
                        <div class="cell large-6">
                            <label>Habilidades:
                                {{form.habilidades}}
                            </label>
                        </div>
                        <div class="cell large-6">
                            <label>Foto:
                                {{form.avatar}}
                            </label>
                        </div>
                        <div class="cell large-6">
                            <button type="submit" class="button success">Guardar</button>
                        </div>


                </form>
        </div>
</div>

{% endblock content %}

templates/empleados/deleted.html
<h1>Deleted!</h1>

templates/empleados/deleteview.html
{% extends 'base.html' %}

{% block title %}
    Eliminar Empleado
{% endblock title %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Eliminar Empleado: {{ object.full_name }}</h1>

                <form class="cell" method="POST">{% csrf_token %}

                    <div class="callout">
                          <h5>¿Está seguro que quiere eliminar este Empleado?</h5>
                            <button type="submit" class="alert button">SÍ</button>
                            <a href="/" class="button"> NO</a>
                    </div>


                </form>
        </div>
</div>

{% endblock content %}

templates/empleados/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ object.full_name}}
{% endblock title %}

{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align=center">
        <div class="cell large-4 card" style="width: 300px; margin-top: 10px">
          <div class="card-divider">
            {{ empleado.get_job_display }}
          </div>
            {% if empleado.avatar %}
                <img src="{{ empleado.avatar.url }}">
            {% else %}
                <img src="{% static 'img/bmw-x5.jpeg' %}">
            {% endif %}
          <div class="card-section">
            <h4>{{ empleado.full_name }}</h4>
            <p>{{ empleado.first_name}} {{ empleado.last_name}}</p>
              <p>{{ empleado.departamento.short_name}}</p>
               <p><span class="label"> Habilidades:</span></p>
              <ul class="vertical menu">
                  {% for h in empleado.habilidades.all %}
                    <li>{{ h.habilidad }}</li>
                  {% endfor %}
              </ul>

          </div>
        </div>
    </div>
</div>


{% endblock content %}

templates/empleados/habilidades.html
<h1>Lista de habilidades</h1>

<ul>
    {% for h in habilidades %}
        <li>{{ h}}</li>
    {% endfor %}
</ul>

templates/empleados/list_all.html
{% extends 'base.html' %}


{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7" >
                <!--aqui va caja de texto-->
                <input type="text" id="kword" name="kword" placeholder="buscar empleado">
            </div>
            <div class="cell large-2">
                <!--aqui va el boton buscar-->
                <button type="submit" class="success button">Buscar</button>
            </div>

        </form>
        <div class="cell">
                aqui va la tabla
            <table>
              <thead>
                <tr>
                  <th width="200">ID</th>
                  <th>Nombres</th>
                  <th width="150">Apellidos</th>
                  <th width="150">Departamento</th>
                    <th width="150">Acción</th>
                </tr>
              </thead>
              <tbody>
                {% for e in empleados %}
                <tr>
                  <td>{{ e.id}}</td>
                  <td>{{ e.first_name}}</td>
                  <td>{{ e.last_name}}</td>
                  <td>{{ e.departamento}}</td>
                    <td><a class="button warning" href="{% url 'empleado_app:empleado_detail' e.id %}">Ver</a></td>
                </tr>
                {% endfor %}
              </tbody>
        </table>
        </div>
        <div class="cel">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                  <ul class="pagination">
                      {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atrás</a>
                    </li>
                      {% endif %}

                      {% for pagina in paginator.page_range %}

                      <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>

                      {% endfor %}

                      {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                        </li>
                      {% endif %}
                  </ul>
            </nav>
            {% endif %}
        </div>
    </div>
   </div>


{% endblock content %}

templates/empleados/list_by_area.html
{% extends 'base.html' %}

{% block title %}
    Lista de empleados por departamento
{% endblock title %}

{% block content %}
    {% include "includes/header.html" %}

    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                Empleado por area
            </div>

        </div>
    </div>
    <div class="cell">
                aqui va la tabla
            <table>
              <thead>
                <tr>
                  <th width="200">ID</th>
                  <th>Nombres</th>
                  <th width="150">Apellidos</th>
                  <th width="150">Departamento</th>
                    <th width="150">Acción</th>
                </tr>
              </thead>
              <tbody>
                {% for e in empleados %}
                <tr>
                  <td>{{ e.id}}</td>
                  <td>{{ e.first_name}}</td>
                  <td>{{ e.last_name}}</td>
                  <td>{{ e.departamento}}</td>
                    <td><a class="button warning" href="{% url 'empleado_app:empleado_detail' e.id %}">Ver</a></td>
                </tr>
                {% endfor %}
              </tbody>
        </table>
    </div>

{% endblock content %}

<h1>Lista de em por dep</h1>

<ul>
    {% for e in object_list %}
        <li>{{ e }}</li>
    {% endfor %}
</ul>

templates/empleados/list_empleados.html
{% extends 'base.html' %}


{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>

        <div class="cell">
                aqui va la tabla
            <table>
              <thead>
                <tr>
                  <th width="200">ID</th>
                  <th>Nombres</th>
                  <th width="150">Apellidos</th>
                  <th width="150">Departamento</th>
                    <th width="150">Acción</th>
                    <th width="150">Acción</th>
                </tr>
              </thead>
              <tbody>
                {% for e in empleados %}
                <tr>
                  <td>{{ e.id}}</td>
                  <td>{{ e.first_name}}</td>
                  <td>{{ e.last_name}}</td>
                  <td>{{ e.departamento}}</td>
                    <td>
                        <a class="button success" href="{% url 'empleado_app:modificar_empleado' e.id %}">Editar</a>
                    </td>
                    <td>
                        <a class="button alert" href="{% url 'empleado_app:eliminar-empleado' e.id %}">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
              </tbody>
        </table>
        </div>
        <div class="cel">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                  <ul class="pagination">
                      {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atrás</a>
                    </li>
                      {% endif %}

                      {% for pagina in paginator.page_range %}

                      <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>

                      {% endfor %}

                      {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                        </li>
                      {% endif %}
                  </ul>
            </nav>
            {% endif %}
        </div>
    </div>
   </div>


{% endblock content %}

templates/empleados/success.html
<h1>Success</h1>

templates/empleados/update.html
{% extends 'base.html' %}

{% block title %}
    Editar Empleado

{% endblock title %}

{% block content %}

{% include "includes/header.html" %}
<div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <h1 class="cell">
                    Modificar datos de empleados
                </h1>
                <div class="cell">
                    <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                        <div class="cell large-6">
                            <label>Nombre:
                                {{form.first_name}}
                            </label>
                        </div>
                        <div class="cell large-6">
                            <label>Apellido:
                                {{form.last_name}}
                            </label>
                        </div>
                        <div class="cell large-6">
                            <label>Trabajo:
                                {{form.job}}
                            </label>
                        </div>
                        <div class="cell large-6">
                            <label>Area:
                                {{form.departamento}}
                            </label>
                        </div>
                        <div class="cell large-6">
                            <label>Habilidades:
                                {{form.habilidades}}
                            </label>
                        </div>
                        <div class="cell">
                            <button type="submit" class="submit success button">Guardar</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
</div>

{% endblock content %}