applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="departamento_app"

urlpatterns = [
    path('new-dep/',
         views.NewDepartamentoView.as_view(),
         name='nuevo_dep'),
    path('listadep/',
         views.DepListView.as_view(),
         name='listadep'),
    path('success_dep/',
         views.NewDepSucView.as_view(),
         name='success_dep'),
]

print(urlpatterns)

applications/empleados/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name ="empleado_app"

urlpatterns = [
    path('',
         views.StartView.as_view(),
         name='inicio'),

    path('listar-todos-empleados/',
         views.ListallEmpleados.as_view(),
         name='empleados-all'),

    path('listar-by-area/<nname>',
         views.ListbyArea.as_view(),
         name='empleados_area'),

    path('listar-empleados-admin',
         views.ListaEmpleadosAdmin.as_view(),
         name='empleados_admin'),

    path('buscar-empleado', views.ListbyKeyword.as_view()),

    path('lista-de-habilidades', views.ListHabEmp.as_view()),

    path('ver-empleado/<pk>/',
         views.EmpDetView.as_view(),
         name='empleado_detail'),

    path('add-empleado/',
         views.EmpCreateView.as_view(),
        name='empleado_add'),

    path('success/',
         views.SuccessView.as_view(),
         name='correcto'),

    path('update-empleado/<pk>/',
         views.EmpUpdView.as_view(),
         name='modificar_empleado'),

    path('deleted/',
         views.DeleteSuccessView.as_view(),
         name='deleted'),
    path('delete-empleado/<pk>',
         views.EmpDelView.as_view(),
         name='eliminar-empleado'),

     ]

urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('applications.home.urls')),
    path('',include('applications.departamento.urls')),
    path('',include('applications.empleados.urls')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
{% load static %}

<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Empleados</li>
      <li>
        <a href="{% url 'empleado_app:empleados-all' %}">Listar</a>
      </li>
      <li><a href="{% url 'departamento_app:listadep' %}">Departamentos</a></li>
      <li><a href="{% url 'empleado_app:empleados_admin' %}">Administrar</a></li>
      <li><a href="{% url 'departamento_app:nuevo_dep' %}">Agregar Departamento</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Buscar empleado"></li>
      <li><a href="{% url 'empleado_app:empleado_add' %}" class="button">Registrar nuevo</a></li>
    </ul>
  </div>
</div>