applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="departamento_app"

urlpatterns = [
    path('new-dep/',
         views.NewDepartamentoView.as_view(),
         name='nuevo_dep'),
    path('listadep/',
         views.DepListView.as_view(),
         name='listadep'),
    path('success_dep/',
         views.NewDepSucView.as_view(),
         name='success_dep'),
]

print(urlpatterns)

applications/empleados/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name ="empleado_app"

urlpatterns = [
    path('',
         views.StartView.as_view(),
         name='inicio'),

    path('listar-todos-empleados/',
         views.ListallEmpleados.as_view(),
         name='empleados-all'),

    path('listar-by-area/<nname>',
         views.ListbyArea.as_view(),
         name='empleados_area'),

    path('listar-empleados-admin',
         views.ListaEmpleadosAdmin.as_view(),
         name='empleados_admin'),

    path('buscar-empleado', views.ListbyKeyword.as_view()),

    path('lista-de-habilidades', views.ListHabEmp.as_view()),

    path('ver-empleado/<pk>/',
         views.EmpDetView.as_view(),
         name='empleado_detail'),

    path('add-empleado/',
         views.EmpCreateView.as_view(),
        name='empleado_add'),

    path('success/',
         views.SuccessView.as_view(),
         name='correcto'),

    path('update-empleado/<pk>/',
         views.EmpUpdView.as_view(),
         name='modificar_empleado'),

    path('deleted/',
         views.DeleteSuccessView.as_view(),
         name='deleted'),
    path('delete-empleado/<pk>',
         views.EmpDelView.as_view(),
         name='eliminar-empleado'),

     ]

urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('applications.home.urls')),
    path('',include('applications.departamento.urls')),
    path('',include('applications.empleados.urls')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models


# Create your models here.

class Departamento(models.Model):
    name = models.CharField('Nombre',max_length=50)
    short_name = models.CharField('Nombre corto',max_length=30,blank=True, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['-name']
        unique_together = ('name','short_name')

    def __str__(self):
        return str(self.id) + '-'+self.name + '-' + self.short_name

applications/departamento/forms.py
from django import forms

class NewDepartmentForm(forms.Form):
    # nombre = forms.CharField(max_length=50)
    # apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    short_name = forms.CharField(max_length=20)

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import ListView, TemplateView
from .forms import NewDepartmentForm
from ..empleados.models import Empleado
from .models import Departamento

class DepListView(ListView):
    template_name = "departamento/lista.html"
    model=Departamento
    context_object_name = 'departamentos'


#FormView. no vinculada con un modelo directamente
class NewDepartamentoView(FormView):
    template_name = 'departamento/new_depart.html'
    form_class = NewDepartmentForm
    success_url = '/success_dep'

    #debemos sobreescribir
    def form_valid(self, form):
        depa=Departamento(
        name=form.cleaned_data['departamento'],
        short_name=form.cleaned_data['short_name'],)
        depa.save()
        return super(NewDepartamentoView,self).form_valid(form)

class NewDepSucView(TemplateView):
    template_name = "departamento/success_dep.html"

# nombre = form.cleaned_data['nombre']
# apellido = form.cleaned_data['apellidos']
# Empleado.objects.create(
#     first_name=nombre,
#     last_name=apellido,
#     job='1',
#     departamento=depa
# )
# return super(NewDepartamentoView,self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}

gwegew
{% block title %}
    Lista de departamentos
{% endblock title %}

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamento in departamentos %}

                        <tr>
                            <td>{{departamento.name}}</td>
                            <td> {{departamento.short_name}}</td>
                            <td>
                                <a class="button warning" href="{% url 'empleado_app:empleados_area' departamento.short_name %}">Ver Empleados</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>
{% endblock content %}

templates/departamento/new_depart.html
{% extends 'base.html' %}

{% block title %}
    Registrar Departamento
{% endblock title %}

{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Registrar Departamento:</h1>
                <form class="cell callout grid-x grid-margin-x" method="POST" >{% csrf_token %}

                        <div class="cell large-6">
                            <label>Departamento:
                                {{form.departamento}}
                            </label>
                        </div>
                        <div class="cell large-6">
                            <label>Nombre Corto:
                                {{form.short_name}}
                            </label>
                        </div>

                        <div class="cell large-6">
                            <button type="submit" class="button success">Guardar</button>
                        </div>
                </form>
        </div>
</div>


{% endblock content %}

templates/departamento/success_dep.html
{% extends 'base.html' %}

{% block title %}
    Success Dep
{% endblock title %}

{% block content %}

{% include "includes/header.html" %}
<div class="grid-container">
    <h1>¡Se ha agregado el departamento con exito!</h1>
</div>

<li><a href="/">Volver a la página principal</a></li>

{% endblock content %}